# Generated by Django 2.2.6 on 2019-10-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.UUID('dc0a6e96-f386-448e-9347-4bac19de0a80'), editable=False, unique=True)),
                ('origin_poin', models.CharField(max_length=100)),
                ('destination_poin', models.CharField(max_length=100)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('bayar', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
