# Generated by Django 2.2.6 on 2019-10-23 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_dirver',
            new_name='is_driver',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d2491db0-debe-40b2-9d53-854c654c1bd8'), editable=False, unique=True),
        ),
    ]
