# Generated by Django 2.2.6 on 2019-10-23 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20191023_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0d26a4cf-619f-4f5f-8bc8-0545d4f4ba76'), editable=False, unique=True),
        ),
    ]
